# various helper functions

# Put on top of rstantools system files.
# deduce comment character based on file extension
.rstantools_noedit <- function(file_name) {
  # comment character
  file_name <- basename(file_name)
  ext <- gsub(".*[.]", "", file_name)
  if(ext == file_name) ext <- ""
  com <- ifelse(tolower(ext) %in% c("r", "", "win"), "#", "//")
  paste0(com, " ", "Generated by rstantools.  Do not edit by hand.")
}

# don't overwrite file warning.
.warning_nowrite <- function(file_name) {
  message("'", file_name, "' already exists.  Not overwritten by rstantools.")
  invisible(NULL)
}

# rstantools system files
.system_file <- function(...) {
  system.file("include", "sys", ..., package = "rstantools")
}

# taken from Rcpp::compileAttributes
# validates package directory
.check_pkgdir <- function(pkgdir) {
  pkgdir <- normalizePath(pkgdir, winslash = "/")
  descFile <- file.path(pkgdir, "DESCRIPTION")
  if (!file.exists(descFile))
    stop("pkgdir must refer to the directory containing an R package")
  pkgdir
}


# create a stan directory
.add_standir <- function(pkgdir, ...) {
  dir_name <- file.path(pkgdir, ...)
  acc <- dir.create(dir_name, recursive = TRUE,
                    showWarnings = FALSE)
  if(!acc) .warning_nowrite(file.path(basename(pkgdir), ...))
  invisible(acc)
}

# add stan file consisting of character vector of file_lines
# don't overwrite unless first line of destination file is .rstantools_noedit
# if noedit, add this to first line of file
.add_stanfile <- function(file_lines, pkgdir, ..., noedit = TRUE) {
  dest_file <- file.path(pkgdir, ...)
  noedit_msg <- .rstantools_noedit(dest_file)
  ## isR <- gsub("[.]R$", "", dest_file) != dest_file
  ## noedit_msg <- paste0(ifelse(isR, "# ", "// "), .rstantools_noedit)
  acc <- !file.exists(dest_file) ||
    (readLines(dest_file, n = 1) == noedit_msg)
  if(acc) {
    if(noedit && (file_lines[1] != noedit_msg)) {
      file_lines <- c(noedit_msg, "", file_lines)
    }
    cat(file_lines, sep = "\n", file = dest_file)
  } else {
    .warning_nowrite(basename(dest_file))
  }
  invisible(acc)
}
